IMASau/Seamap

frontend/src/cljs/imas_seamap/components.cljs
frontend/src/cljs/imas_seamap/core.cljs
frontend/src/cljs/imas_seamap/db.cljs
frontend/src/cljs/imas_seamap/events.cljs
frontend/src/cljs/imas_seamap/interop/ui_controls.cljs
frontend/src/cljs/imas_seamap/subs.cljs
frontend/src/cljs/imas_seamap/views.cljs
frontend/src/stories/Drawer/Drawer.jsx
frontend/src/stories/Drawer/Drawer.stories.jsx

A React component for a drawer has been created (https://blueprintjs.com/docs/#core/components/drawer).
The drawer is currently used in a basic "seamap drawer" component, which has its state (opened/closed) stored in the frontend db.
There are events to change the seamap drawer state, including a toggle hooked up to a hotkey ('a', which might need to be changed).
The seamap drawer is not currently in use, but the component can easily be added to the layout app in views.cljs

Feature: (ISA-120) Drawer component

---

frontend/resources/public/css/app.css
frontend/src/cljs/imas_seamap/components.cljs
frontend/src/cljs/imas_seamap/events.cljs
frontend/src/cljs/imas_seamap/map/events.cljs
frontend/src/cljs/imas_seamap/views.cljs

Just some simple changes that add functionality to the drawer.
Only one hack that I'm concerned with and want someone to take a look at: for the subs in "child" panels to update, there needs to be an unnecessary sub in "base-panel" (line 635).

Feature: (ISA-120) Drawer map layers panels

---

frontend/src/cljs/imas_seamap/specs/app_state.cljs

Just a few updates to the app-state spec to accomodate for the drawer, drawer panels, base layers, and layer tweaks.
Drawer panels spec will need to be updated when pull request #42 is through.

Feature: (ISA-129) Update app-state spec

---

frontend/resources/public/css/app.css
frontend/src/cljs/imas_seamap/core.cljs
frontend/src/cljs/imas_seamap/db.cljs
frontend/src/cljs/imas_seamap/events.cljs
frontend/src/cljs/imas_seamap/map/events.cljs
frontend/src/cljs/imas_seamap/specs/app_state.cljs
frontend/src/cljs/imas_seamap/subs.cljs
frontend/src/cljs/imas_seamap/views.cljs

New drawer on right, and renaming "seamap drawer" to "left drawer".
Not much to review here, just for organisation.

Feature: (ISA-137) Right panel

---

frontend/src/cljs/imas_seamap/map/events.cljs
frontend/src/cljs/imas_seamap/map/utils.cljs

Fixes https://jira.its.utas.edu.au/browse/ISA-88
Ensures that results returned from all servers are then combined into the single popup that is displayed.

Feature: (ISA-88) GFI Multiserver Logic

---

frontend/src/cljs/imas_seamap/core.cljs
frontend/src/cljs/imas_seamap/events.cljs
frontend/src/cljs/imas_seamap/map/events.cljs
frontend/src/cljs/imas_seamap/map/subs.cljs
frontend/src/cljs/imas_seamap/map/utils.cljs
frontend/src/cljs/imas_seamap/map/views.cljs
frontend/src/cljs/imas_seamap/specs/app_state.cljs
frontend/src/cljs/imas_seamap/views.cljs

Making some effort towards ISA-32 (https://jira.its.utas.edu.au/browse/ISA-32)
The changes below are hardly comprehensive in removing category-specific logic, and I expect that at some point we'll probably return to remove even more stuff.
Also some minor code adjustments for readability.

Feature: (ISA-32) treat layer categories equally

---

frontend/resources/public/css/app.css
frontend/src/cljs/imas_seamap/interop/leaflet.cljs
frontend/src/thirdparty/leaflet-coordinates.js

This bugfix fixes the issue of longitude in the coordinates display increasing indefinitely (above the usual -180 to 180 bounds).
This is an issue with the react-leaflet-coordinates package, so its usage has been replaced with a modified version that fixes this issue.

Bugfix: (ISA-143) Lat-lng display

---

frontend/package.json
frontend/resources/public/css/app.css
frontend/resources/public/index.html
frontend/src/cljs/imas_seamap/components.cljs
frontend/src/cljs/imas_seamap/core.cljs
frontend/src/cljs/imas_seamap/db.cljs
frontend/src/cljs/imas_seamap/events.cljs
frontend/src/cljs/imas_seamap/interop/ui_controls.cljs
frontend/src/cljs/imas_seamap/map/events.cljs
frontend/src/cljs/imas_seamap/map/subs.cljs
frontend/src/cljs/imas_seamap/map/utils.cljs
frontend/src/cljs/imas_seamap/subs.cljs
frontend/src/cljs/imas_seamap/views.cljs
frontend/src/ui/Omnibar/Omnibar.css
frontend/src/ui/Omnibar/Omnibar.jsx
frontend/src/ui/Omnibar/Omnibar.stories.jsx
frontend/yarn.lock

Added Omnibar component (https://blueprintjs.com/docs/versions/3/#select/omnibar).
Omnibar component has been integrated in the app to allow searching through all layers, and activates a layer when it is selected.
Layers search is currently accessed via shift+s, but can be changed. Later some visual feedback to the user will need to be added to show them that their selected layer has been activated (maybe a toast-like message like the one we have when the user copies the share URL?)

Feature: (ISA-145) Omnibar search

---

frontend/resources/public/css/app.css
frontend/src/cljs/imas_seamap/map/views.cljs
frontend/src/thirdparty/leaflet.scalefactor.js

https://jira.its.utas.edu.au/browse/ISA-126
Added leaflet.scalefactor code (https://github.com/MarcChasse/leaflet.ScaleFactor) with a few modifications that allows it to work on the map. Displays the current scale factor in the bottom-left, as expected.

Feature: (ISA-126) Map scale ratio

---

frontend/src/cljs/imas_seamap/core.cljs
frontend/src/cljs/imas_seamap/events.cljs
frontend/src/cljs/imas_seamap/map/events.cljs
frontend/src/cljs/imas_seamap/map/utils.cljs
frontend/src/cljs/imas_seamap/views.cljs

Solves https://jira.its.utas.edu.au/browse/ISA-150
Some new events have been added, with code to open a layer in the catalogue and focus that layer on the map when it is selected in the layers search omnibar.

Feature: (ISA-150) Focus catalogue layer click

---

frontend/src/cljs/imas_seamap/map/events.cljs

Automatically centering popup when GFI request is made

Feature: (ISA-4) Automatically centre popup

---

backend/catalogue/models.py
backend/catalogue/serializers.py
backend/catalogue/viewsets.py
backend/webapp/urls.py
frontend/src/cljs/imas_seamap/core.cljs
frontend/src/cljs/imas_seamap/db.cljs
frontend/src/cljs/imas_seamap/events.cljs
frontend/src/cljs/imas_seamap/map/events.cljs
frontend/src/cljs/imas_seamap/map/subs.cljs
frontend/src/cljs/imas_seamap/map/utils.cljs
frontend/src/cljs/imas_seamap/specs/app_state.cljs
frontend/src/cljs/imas_seamap/utils.cljs
frontend/src/cljs/imas_seamap/views.cljs

https://jira.its.utas.edu.au/browse/ISA-135
Adds category info to the DB, and uses new category display name field for the catalogue buttons and panels text.

Feature: (ISA-135) Remove category specific logic (catalogue panels)

---

frontend/src/cljs/imas_seamap/map/subs.cljs
frontend/src/cljs/imas_seamap/map/utils.cljs
frontend/src/cljs/imas_seamap/views.cljs

https://jira.its.utas.edu.au/browse/ISA-165
Sorting by category (display name), then data classification, then id.
Category display name added to layer search keywords.

Feature: (ISA-165) Sorting omnisearch results

---

backend/catalogue/models.py
backend/catalogue/serializers.py
frontend/src/cljs/imas_seamap/core.cljs
frontend/src/cljs/imas_seamap/db.cljs
frontend/src/cljs/imas_seamap/events.cljs
frontend/src/cljs/imas_seamap/map/events.cljs
frontend/src/cljs/imas_seamap/map/subs.cljs
frontend/src/cljs/imas_seamap/map/utils.cljs
frontend/src/cljs/imas_seamap/specs/app_state.cljs
frontend/src/cljs/imas_seamap/views.cljs

[ISA-159](https://jira.its.utas.edu.au/browse/ISA-159)
Does all the stuff in the ticket.
Later update may be required if we decide to go for an extra column in the categories table for the category icon.

Feature: (ISA-159) Custom sidebar categories

---

frontend/src/cljs/imas_seamap/map/events.cljs
frontend/src/cljs/imas_seamap/map/utils.cljs
frontend/src/cljs/imas_seamap/map/views.cljs

[ISA-166](https://jira.its.utas.edu.au/browse/ISA-166)
Neater code, and quick patch fix on the source of the bug (React Leaflet base layers control rendering layers in the order they are received).

Bugfix: (ISA-166) Composite basemap sorting

---

frontend/src/cljs/imas_seamap/map/events.cljs
frontend/src/cljs/imas_seamap/map/views.cljs

[ISA-171](https://jira.its.utas.edu.au/browse/ISA-171)
A few fixes for usability

Feature: (ISA-171) GFI viewport pan focus issues

---

frontend/src/cljs/imas_seamap/components.cljs
frontend/src/cljs/imas_seamap/views.cljs
frontend/src/ui/PanelStack/PanelStack.jsx
frontend/src/ui/css/app.scss

[ISA-177](https://jira.its.utas.edu.au/browse/ISA-177)
Iframe and panel stack worked well for this. Nothing too interesting has been added, so there shouldn't be too much to worry about there.

Feature: (ISA-177) Data coverage report UI

---

frontend/src/cljs/imas_seamap/components.cljs
frontend/src/cljs/imas_seamap/views.cljs
frontend/src/ui/css/floating-pills.scss

[ISA-183](https://jira.its.utas.edu.au/browse/ISA-183)
Pop out menu floating pills, which can contain whatever content we wish. We can get to adding controls to the menu when we know what we want them to do.

Feature: (ISA-183) Richer floating pill controls

---

backend/habitat/viewsets.py
backend/webapp/urls.py
frontend/src/cljs/imas_seamap/core.cljs
frontend/src/cljs/imas_seamap/db.cljs
frontend/src/cljs/imas_seamap/events.cljs
frontend/src/cljs/imas_seamap/map/events.cljs
frontend/src/cljs/imas_seamap/map/subs.cljs
frontend/src/cljs/imas_seamap/specs/app_state.cljs
frontend/src/cljs/imas_seamap/utils.cljs
frontend/src/cljs/imas_seamap/views.cljs
frontend/src/ui/css/app.scss

[ISA-185](https://jira.its.utas.edu.au/browse/ISA-185)
Users are now able to view the statistics individually for AMP, IMCRA, and MEOW boundaries. Frontend changes with new boundary selection tabs to accomodate the three different boundary types. Backend changes to accomodate queries for IMCRA and MEOW boundaries.

Feature: (ISA-185) AMP, IMCRA, and MEOW boundary selection

---

database/Functions/HABITAT_OBS_GLOBALARCHIVE_intersections.sql
database/Functions/HABITAT_OBS_SEDIMENT_intersections.sql
database/Functions/HABITAT_OBS_SQUIDLE_intersections.sql
database/Procedures/Update_AMP_BOUNDARY.sql
database/Procedures/Update_HABITAT_OBS.sql
database/Procedures/Update_IMCRA_BOUNDARY.sql
database/Procedures/Update_MEOW_BOUNDARY.sql
database/Tables/BOUNDARY_AMP_HABITAT_OBS_GLOBALARCHIVE.sql
database/Tables/BOUNDARY_AMP_HABITAT_OBS_SEDIMENT.sql
database/Tables/BOUNDARY_AMP_HABITAT_OBS_SQUIDLE.sql
database/Tables/BOUNDARY_IMCRA_HABITAT_OBS_GLOBALARCHIVE.sql
database/Tables/BOUNDARY_IMCRA_HABITAT_OBS_SEDIMENT.sql
database/Tables/BOUNDARY_IMCRA_HABITAT_OBS_SQUIDLE.sql
database/Tables/BOUNDARY_MEOW_HABITAT_OBS_GLOBALARCHIVE.sql
database/Tables/BOUNDARY_MEOW_HABITAT_OBS_SEDIMENT.sql
database/Tables/BOUNDARY_MEOW_HABITAT_OBS_SQUIDLE.sql
database/Views/VW_HABITAT_OBS_GLOBALARCHIVE.sql
database/Views/VW_HABITAT_OBS_SEDIMENT.sql
database/Views/VW_HABITAT_OBS_SQUIDLE.sql

[ISA-161](https://jira.its.utas.edu.au/browse/ISA-161)
New database objects to support habitat observations.

Feature: (ISA-161) Habitat observations database objects

---

backend/habitat/viewsets.py
backend/webapp/urls.py
database/Functions/HABITAT_OBS_SQUIDLE_intersections.sql
database/Views/VW_HABITAT_OBS_SQUIDLE.sql
frontend/src/cljs/imas_seamap/core.cljs
frontend/src/cljs/imas_seamap/db.cljs
frontend/src/cljs/imas_seamap/map/events.cljs
frontend/src/cljs/imas_seamap/specs/app_state.cljs

[ISA-161](https://jira.its.utas.edu.au/browse/ISA-161)
~~Habitat observations in backend and used by frontend to update the app state. SQUIDLE observations query in the backend will need changes shortly when Emma comes through on some column updates.~~
Edit: SQUIDLE stuff has been updated and the habitat observations queries work as intended 🙂

Feature: (ISA-161) Habitat observations queries

---

frontend/src/cljs/imas_seamap/core.cljs
frontend/src/cljs/imas_seamap/map/subs.cljs
frontend/src/cljs/imas_seamap/specs/app_state.cljs
frontend/src/cljs/imas_seamap/views.cljs
frontend/src/ui/css/app.scss

[ISA-164](https://jira.its.utas.edu.au/browse/ISA-164)
~~Basic UI up for habitat observations until we have a better idea of what we want it to look like (hopefully this will also spark some ideas of what is needed 👍 ).~~
Edit: with the additional information received from Emma, I'm working on matching the desired UI more closely.

Feature: (ISA-164) Habitat observations UI

---

backend/habitat/viewsets.py
frontend/src/cljs/imas_seamap/db.cljs
frontend/src/cljs/imas_seamap/map/events.cljs
frontend/src/cljs/imas_seamap/specs/app_state.cljs
frontend/src/cljs/imas_seamap/views.cljs
frontend/src/ui/css/app.scss

[ISA-161](https://jira.its.utas.edu.au/browse/ISA-161) & [ISA-164](https://jira.its.utas.edu.au/browse/ISA-164)
Querying summary stats of habitat observations in backend and displaying them in the habitat observations UI.

Feature: (ISA-161 & ISA-164) Habitat observations summary UI

---

backend/habitat/viewsets.py
database/Procedures/UpdateBathymetry.sql
database/Procedures/UpdateHabitat.sql
database/Procedures/Update_AMP_BOUNDARY.sql
database/Procedures/Update_IMCRA_BOUNDARY.sql
database/Procedures/Update_MEOW_BOUNDARY.sql
database/Tables/BOUNDARY_AMP_BATHYMETRY.sql
database/Tables/BOUNDARY_AMP_HABITAT.sql
database/Tables/BOUNDARY_IMCRA_BATHYMETRY.sql
database/Tables/BOUNDARY_IMCRA_HABITAT.sql
database/Tables/BOUNDARY_MEOW_BATHYMETRY.sql
database/Tables/BOUNDARY_MEOW_HABITAT.sql

Dependent on [#86](https://github.com/IMASau/Seamap/pull/86)
Just a significant speed improvement for the habitat and bathymetry statistics queries by using precomputed geometry areas in the precomputed tables.

Feature: (ISA-161) Precomputed areas

---

frontend/src/cljs/imas_seamap/components.cljs
frontend/src/cljs/imas_seamap/core.cljs
frontend/src/cljs/imas_seamap/db.cljs
frontend/src/cljs/imas_seamap/map/events.cljs
frontend/src/cljs/imas_seamap/specs/app_state.cljs
frontend/src/cljs/imas_seamap/state_of_knowledge/events.cljs
frontend/src/cljs/imas_seamap/state_of_knowledge/subs.cljs
frontend/src/cljs/imas_seamap/state_of_knowledge/utils.cljs
frontend/src/cljs/imas_seamap/state_of_knowledge/views.cljs
frontend/src/cljs/imas_seamap/views.cljs
frontend/src/ui/css/floating-pills.scss
frontend/src/ui/css/state-of-knowledge.scss

[ISA-195](https://jira.its.utas.edu.au/browse/ISA-195)
Moved the state of knowledge boundary controls into pills, with some new features that trigger on boundary selection, like panning to the extent.
_(A small aside: I find this feature quite satisfying to use 😄)_
Small bugfixes since the screenshots below were taken, but mostly the same.

Feature: (ISA-195) State of knowledge pills

---

backend/.gitignore
backend/base_requirements.txt
backend/catalogue/management/commands/generate_survey_graphs.py
database/Views/VW_TIMELINE_COUNT_STATS_NETWORKS.sql
database/Views/VW_TIMELINE_COUNT_STATS_PARKS.sql

Retrieves survey data from the database, and then generates graphs showing the number of surveys conducted over time.
Generates graphs showing data for all years, and only data post-2000.
Generated graphs stored in media directory.

Feature: (ISA-192) Generate survey graphs

---

frontend/src/cljs/imas_seamap/map/views.cljs
frontend/src/cljs/imas_seamap/views.cljs

[ISA-214](https://jira.its.utas.edu.au/browse/ISA-214)
This ended up being way less hacky then I thought it would in a lot of places; I thought I'd be having a lot of issues fighting with Leaflet Draw.
Omnisearch button also added.
Before:
After:

Feature: (ISA-214) Move tools to small controls

---

frontend/src/cljs/imas_seamap/core.cljs
frontend/src/cljs/imas_seamap/events.cljs
frontend/src/cljs/imas_seamap/map/events.cljs
frontend/src/cljs/imas_seamap/state_of_knowledge/events.cljs
frontend/src/cljs/imas_seamap/utils.cljs

[ISA-224](https://jira.its.utas.edu.au/browse/ISA-224)
Changes as described in ticket. Fixed a small set of bugs for a few events where the encoded state being used for put-hash was the old state rather than the event's updated state.

Feature: (ISA-224) Serialised URL - remember more things

---

frontend/src/cljs/imas_seamap/components.cljs
frontend/src/cljs/imas_seamap/core.cljs
frontend/src/cljs/imas_seamap/db.cljs
frontend/src/cljs/imas_seamap/map/events.cljs
frontend/src/cljs/imas_seamap/specs/app_state.cljs
frontend/src/cljs/imas_seamap/state_of_knowledge/events.cljs
frontend/src/cljs/imas_seamap/state_of_knowledge/subs.cljs
frontend/src/cljs/imas_seamap/state_of_knowledge/views.cljs
frontend/src/cljs/imas_seamap/utils.cljs
frontend/src/ui/css/app.scss
frontend/src/ui/css/state-of-knowledge.scss

[ISA-225](https://jira.its.utas.edu.au/browse/ISA-225)
**Prerequisites:** PR #105
Ability to toggle on certain layers from the state of knowledge panel.

Feature: (ISA-225) State of knowledge layers toggle

---

frontend/src/cljs/imas_seamap/core.cljs
frontend/src/cljs/imas_seamap/db.cljs
frontend/src/cljs/imas_seamap/map/events.cljs
frontend/src/cljs/imas_seamap/map/views.cljs
frontend/src/cljs/imas_seamap/specs/app_state.cljs

[ISA-233](https://jira.its.utas.edu.au/browse/ISA-233)
Pans to a popup once loaded if that popup will be out of bounds. Doesn't pan if the entire popup is within the bounds of the map view. Only pans the amount needed to show the entire popup in the view.

Feature: (ISA-233) Popup panning

---

frontend/src/cljs/imas_seamap/core.cljs
frontend/src/cljs/imas_seamap/map/events.cljs
frontend/src/cljs/imas_seamap/map/views.cljs
frontend/src/cljs/imas_seamap/subs.cljs

[ISA-246](https://jira.its.utas.edu.au/browse/ISA-246)
Loading spinner only appear after 300ms, as described.

Feature (ISA-246) Delay loading spinner

---

frontend/src/cljs/imas_seamap/core.cljs
frontend/src/cljs/imas_seamap/map/events.cljs
frontend/src/cljs/imas_seamap/state_of_knowledge/events.cljs
frontend/src/cljs/imas_seamap/utils.cljs

[ISA-264](https://jira.its.utas.edu.au/browse/ISA-264)
Nothing major, but have got to remember to update the code for `:add-layer-below-layer` PR #120 goes through.

(ISA-264) State of knowledge layers tweaks

---

frontend/src/cljs/imas_seamap/map/subs.cljs
frontend/src/cljs/imas_seamap/map/utils.cljs
frontend/src/cljs/imas_seamap/views.cljs

[ISA-262](https://jira.its.utas.edu.au/browse/ISA-262)
Added a proper sort order to the omnisearch.

(ISA-262) Omnisearch sort order

---

.github/workflows/buildfrontend.yml
frontend/resources/public/index.html
frontend/shadow-cljs.edn
frontend/src/cljs/imas_seamap/core.cljs
frontend/src/cljs/imas_seamap/db.cljs
frontend/src/cljs/imas_seamap/events.cljs
frontend/src/cljs/imas_seamap/map/events.cljs
frontend/src/cljs/imas_seamap/map/utils.cljs
frontend/src/cljs/imas_seamap/specs/app_state.cljs
frontend/src/cljs/imas_seamap/state_of_knowledge/events.cljs
frontend/src/cljs/imas_seamap/state_of_knowledge/subs.cljs
frontend/src/cljs/imas_seamap/subs.cljs
frontend/src/cljs/imas_seamap/views.cljs

[ISA-289](https://jira.its.utas.edu.au/browse/ISA-289)
URL db config has changed so that it's determined at boot based on the app page URL. If we want to specify additional base URL configs, all we have to do is add them to the app's default db config.

(ISA-289) URL base init refactor

---

frontend/src/cljs/imas_seamap/map/layer_views.cljs
frontend/src/cljs/imas_seamap/views.cljs
frontend/src/ui/css/layer-card.scss

Just an additional PR to fix a few problems with the catalogue entry for the main national layer

(ISA-263) Main national layer card functionality

---

backend/catalogue/management/commands/retrieve_bathymetry_statistics.py
backend/catalogue/management/commands/retrieve_habitat_statistics.py
wordpress/plugins/region-report/single-region_report.php
wordpress/plugins/region-report/style.css

Small bugfix tweaks like mapped area in tables and region headings for region reports.

(ISA-203) Region report tweaks for first dev deployment

---

backend/catalogue/management/commands/retrieve_research_effort.py
wordpress/plugins/region-report/single-region_report.php
wordpress/plugins/region-report/style.css

[ISA-192](https://jira.its.utas.edu.au/browse/ISA-192)
Adaptive research effort graphs for the region report data pages. Data for the graphs is queried and stored in the Django server media storage, where it is then retrieved via AJAX and displayed as a graph using Vega.
You cannot argue with the results:

(ISA-192) Region reports research effort graphs

---

backend/catalogue/serializers.py
wordpress/plugins/region-report/single-region_report.php
wordpress/plugins/region-report/style.css

[ISA-191](https://jira.its.utas.edu.au/browse/ISA-191)
Map overview image added to region report wordpress page.

Feature: (ISA-191) Static map overview image

---

wordpress/plugins/region-report/region-report.php
wordpress/plugins/region-report/single-region_report.php

[ISA-241](https://jira.its.utas.edu.au/browse/ISA-241)
Settings page added to region reports to help with publishing support. Now the base URLs used by the region report pages can be configured site-wide:

(ISA-241) Region Report Settings Page

---

backend/habitat/viewsets.py
database/Functions/AMP_BOUNDARY_geom.sql
database/Procedures/UpdateBathymetry.sql
database/Procedures/UpdateHabitat.sql
database/Procedures/Update_AMP_BOUNDARY.sql
database/Procedures/Update_HABITAT_OBS.sql
database/Tables/BOUNDARY_AMP_BATHYMETRY.sql
database/Tables/BOUNDARY_AMP_HABITAT.sql
database/Tables/BOUNDARY_AMP_HABITAT_OBS_GLOBALARCHIVE.sql
database/Tables/BOUNDARY_AMP_HABITAT_OBS_SEDIMENT.sql
database/Tables/BOUNDARY_AMP_HABITAT_OBS_SQUIDLE.sql
database/Views/VW_BOUNDARY_AMP.sql
frontend/src/cljs/imas_seamap/core.cljs
frontend/src/cljs/imas_seamap/db.cljs
frontend/src/cljs/imas_seamap/specs/app_state.cljs
frontend/src/cljs/imas_seamap/state_of_knowledge/events.cljs
frontend/src/cljs/imas_seamap/state_of_knowledge/subs.cljs
frontend/src/cljs/imas_seamap/state_of_knowledge/utils.cljs
frontend/src/cljs/imas_seamap/state_of_knowledge/views.cljs

[ISA-331](https://jira.its.utas.edu.au/browse/ISA-331)
Database and app updates have been made to allow the user to filter the AMP boundaries by the zone ID:

Feature: (ISA-331) AMP Boundaries Zone ID Filter

---

backend/habitat/viewsets.py
frontend/src/cljs/imas_seamap/core.cljs
frontend/src/cljs/imas_seamap/db.cljs
frontend/src/cljs/imas_seamap/specs/app_state.cljs
frontend/src/cljs/imas_seamap/state_of_knowledge/events.cljs
frontend/src/cljs/imas_seamap/state_of_knowledge/subs.cljs
frontend/src/cljs/imas_seamap/state_of_knowledge/utils.cljs
frontend/src/cljs/imas_seamap/state_of_knowledge/views.cljs
frontend/src/cljs/imas_seamap/views.cljs

[ISA-330](https://jira.its.utas.edu.au/browse/ISA-330)
Simple explanation is that this code only allows the user to select zones that are within the currently selected boundary and vice-versa:

(ISA-330) State of Knowledge Zone Filtering

---

frontend/src/cljs/imas_seamap/views.cljs
frontend/src/ui/css/app.scss
frontend/src/ui/css/blueprint-overrides.scss
frontend/src/ui/css/wordpress.css

Welcome dialogue follows Nat's redesign

UX Sweep: Welcome Dialogue

---

frontend/src/cljs/imas_seamap/views.cljs
frontend/src/index.scss
frontend/src/ui/css/app.scss

[ISA-340](https://jira.its.utas.edu.au/browse/ISA-340)
Design:
Result:

UX Sweep: (ISA-340) Welcome Dialogue

---

frontend/src/cljs/imas_seamap/state_of_knowledge/views.cljs
frontend/src/ui/css/app.scss
frontend/src/ui/css/blueprint-overrides.scss
frontend/src/ui/css/state-of-knowledge.scss

[ISA-338](https://jira.its.utas.edu.au/browse/ISA-338)
Design:
Result:

UX Sweep: (ISA-338) State of Knowledge

---

frontend/src/cljs/imas_seamap/state_of_knowledge/views.cljs
frontend/src/ui/css/app.scss
frontend/src/ui/css/blueprint-overrides.scss
frontend/src/ui/css/story-maps.scss

[ISA-339](https://jira.its.utas.edu.au/browse/ISA-339)
Design:
Result:

Ux Sweep: (ISA-339) Story Maps

---

frontend/src/cljs/imas_seamap/components.cljs
frontend/src/cljs/imas_seamap/tas_marine_atlas/views.cljs
frontend/src/cljs/imas_seamap/views.cljs
frontend/src/index.scss
frontend/src/ui/Drawer/Drawer.jsx
frontend/src/ui/css/app.scss
frontend/src/ui/css/blueprint-overrides.scss
frontend/src/ui/css/left-drawer.scss

[ISA-352](https://jira.its.utas.edu.au/browse/ISA-352)
Design:
Result:

UX Sweep: (ISA-352) LHS Header

---

frontend/src/cljs/imas_seamap/blueprint.cljs
frontend/src/cljs/imas_seamap/map/layer_views.cljs
frontend/src/cljs/imas_seamap/tas_marine_atlas/views.cljs
frontend/src/cljs/imas_seamap/views.cljs
frontend/src/index.scss
frontend/src/ui/blueprint.scss
frontend/src/ui/css/app.scss
frontend/src/ui/css/blueprint-overrides.scss
frontend/src/ui/css/layer-card.scss
frontend/src/ui/css/left-drawer.scss

[ISA-353](https://jira.its.utas.edu.au/browse/ISA-353)
Design:
Result:

UX Sweep: (ISA-353) LHS Catalogue

---

frontend/src/cljs/imas_seamap/components.cljs
frontend/src/cljs/imas_seamap/map/layer_views.cljs
frontend/src/cljs/imas_seamap/views.cljs
frontend/src/ui/css/blueprint-overrides.scss
frontend/src/ui/css/layer-card.scss
frontend/src/ui/css/left-drawer.scss

[ISA-354](https://jira.its.utas.edu.au/browse/ISA-354)
Small amount of guesswork from the provided designs was necessary, but I think the result was rather nice.
Design:
Result:

UX Sweep: (ISA-354) LHS Active Layers

---

wordpress/plugins/region-report/region-report.js
wordpress/plugins/region-report/single-region_report.php
wordpress/plugins/region-report/style.scss

[ISA-231](https://jira.its.utas.edu.au/browse/ISA-231)

(ISA-231) Region Report Print Friendliness

---

frontend/src/cljs/imas_seamap/story_maps/views.cljs
frontend/src/ui/css/blueprint-overrides.scss
frontend/src/ui/css/story-maps.scss

[ISA-355](https://jira.its.utas.edu.au/browse/ISA-355)

UX Sweep: (ISA-355) LHS Featured Maps

---

backend/catalogue/serializers.py
backend/catalogue/viewsets.py
backend/habitat/viewsets.py
backend/webapp/urls.py
frontend/src/cljs/imas_seamap/core.cljs
frontend/src/cljs/imas_seamap/db.cljs
frontend/src/cljs/imas_seamap/events.cljs
frontend/src/cljs/imas_seamap/map/events.cljs
frontend/src/cljs/imas_seamap/state_of_knowledge/events.cljs
frontend/src/cljs/imas_seamap/state_of_knowledge/subs.cljs
frontend/src/cljs/imas_seamap/state_of_knowledge/views.cljs
frontend/src/cljs/imas_seamap/utils.cljs
frontend/src/ui/css/blueprint-overrides.scss
frontend/src/ui/css/left-drawer.scss
frontend/src/ui/css/state-of-knowledge.scss

[ISA-371](https://jira.its.utas.edu.au/browse/ISA-371)
Added breadcrumb links to change filters in the state of knowledge, and a hyperlink to the corresponding region report page when an appropriate corresponding region is selected.

(ISA-371) Region Report Pages and Breadcrumbs Link

---

etl/email_manager.py
etl/extractor.py
etl/main.py
etl/settings.py
etl/transformer.py

Catch db connection exception and send an email.

Iwa 955 capture database connection issue

---

frontend/src/cljs/imas_seamap/core.cljs
frontend/src/cljs/imas_seamap/db.cljs
frontend/src/cljs/imas_seamap/events.cljs
frontend/src/cljs/imas_seamap/map/events.cljs
frontend/src/cljs/imas_seamap/map/layer_views.cljs
frontend/src/cljs/imas_seamap/subs.cljs
frontend/src/cljs/imas_seamap/tas_marine_atlas/core.cljs
frontend/src/cljs/imas_seamap/tas_marine_atlas/events.cljs
frontend/src/cljs/imas_seamap/utils.cljs

[ISA-313](https://jira.its.utas.edu.au/browse/ISA-313)
App now remembers national layer filters and selected tab.

(ISA-313) Remember National Layer State

---

backend/base_requirements.txt
backend/catalogue/management/commands/rebuild_feature_index.py
backend/habitat/viewsets.py
backend/webapp/urls.py
database/Tables/TasMarineAtlas/layer_feature.sql
frontend/src/cljs/imas_seamap/map/layer_views.cljs
frontend/src/cljs/imas_seamap/tas_marine_atlas/core.cljs
frontend/src/cljs/imas_seamap/tas_marine_atlas/db.cljs
frontend/src/cljs/imas_seamap/tas_marine_atlas/events.cljs
frontend/src/cljs/imas_seamap/tas_marine_atlas/subs.cljs
frontend/src/cljs/imas_seamap/tas_marine_atlas/views.cljs
frontend/src/cljs/imas_seamap/views.cljs
frontend/src/ui/css/app.scss
frontend/src/ui/css/layer-card.scss

[ISA-395](https://jira.its.utas.edu.au/browse/ISA-395)
Allows the user to select a region and find out what layers overlap with that region.
Spatial index maintained by Django management command.

Feature: (ISA-395) data in region

---

backend/catalogue/management/commands/build_feature_index_end.py
backend/catalogue/management/commands/build_feature_index_layer.py
backend/catalogue/management/commands/build_feature_index_start.py
database/Tables/TasMarineAtlas/layer_feature_temp.sql

[ISA-441](https://jira.its.utas.edu.au/browse/ISA-441)
Doesn't wipe table when building feature index.

Feature: (ISA-441) Smarter Feature Index

---

backend/base_requirements.txt
backend/catalogue/management/commands/generate_layer_previews.py
backend/catalogue/models.py

Added support for creating previews of vector layers. Probably doesn't cover all cases yet, so some testing is necessary.

Feature: (ISA-507) Vector Layer Previews

---

frontend/src/cljs/imas_seamap/core.cljs
frontend/src/cljs/imas_seamap/events.cljs
frontend/src/cljs/imas_seamap/fx.cljs
frontend/src/cljs/imas_seamap/tas_marine_atlas/core.cljs
frontend/src/cljs/imas_seamap/tas_marine_atlas/events.cljs

Fixes [ISA-554](https://utas.atlassian.net/browse/ISA-554) by implementing local storage solution mentioned [here](https://utas.atlassian.net/browse/ISA-554?focusedCommentId=427889).

Feature: Local Storage

---

.github/workflows/buildfrontend.yml

Separated release job from the build job, and simplified asset name in release

Feature: Better releases

---

backend/catalogue/models.py
frontend/custom_modules/leaflet-tilelayer-wmts/LICENSE
frontend/custom_modules/leaflet-tilelayer-wmts/README.md
frontend/custom_modules/leaflet-tilelayer-wmts/leaflet-tilelayer-wmts.js
frontend/custom_modules/leaflet-tilelayer-wmts/package.json
frontend/package.json
frontend/shadow-cljs.edn
frontend/src/cljs/imas_seamap/db.cljs
frontend/src/cljs/imas_seamap/interop/leaflet.cljs
frontend/src/cljs/imas_seamap/map/utils.cljs
frontend/src/cljs/imas_seamap/map/views.cljs
frontend/src/cljs/imas_seamap/seamap_antarctica/core.cljs
frontend/src/cljs/imas_seamap/seamap_antarctica/db.cljs
frontend/src/cljs/imas_seamap/seamap_antarctica/events.cljs
frontend/src/cljs/imas_seamap/seamap_antarctica/map/views.cljs
frontend/src/cljs/imas_seamap/seamap_antarctica/views.cljs
frontend/src/cljs/imas_seamap/views.cljs
frontend/yarn.lock

[ISA-625](https://utas.atlassian.net/browse/ISA-625)
Added a new standalone app for Seamap Antarctica.
It diverges from Seamap Antarctica by using a polar CRS for the map.
Now supports WMTS layers for the polar basemap (WIP feature, currently only covers very specific basemap we're using)

ISA-625: Proof-of-concept test polar coordinate system and layer
