IMASau/Seamap

frontend/resources/public/css/app.css, frontend/src/cljs/imas_seamap/components.cljs, frontend/src/cljs/imas_seamap/map/views.cljs, frontend/src/cljs/imas_seamap/views.cljs
Google Saps style pill buttons added over top of map. Placeholder button functionality used until we know what we actually want to use them for.
Quite CSS heavy, but I think I accounted for all the sidebar states accurately. Got to remember to account for the different absolute positioning when we decide we want it to move with the drawer rather than the Leaflet panel.
=> Feature: (ISA-136) Google Maps pills

backend/habitat/viewsets.py, database/Functions/path_intersections.sql, database/Types/HabitatTableType.sql, frontend/src/cljs/imas_seamap/plot/views.cljs, frontend/src/ui/PanelStack/PanelStack.jsx
Updated the transect query to include the layer name of the polygon intersected by each segment. Updates to both `HabitatTableType.sql` and `path_intersections.sql` that have been applied to the dev database.
Transect tooltip now includes layer name for each segment.
=> Feature: (ISA-1) transect layer names

frontend/src/cljs/imas_seamap/views.cljs
Simple change: removed all the additional sidebar tabs.
The tab enclosing the active layers tab content hasn't been removed because it would destroy the current styling and also leave the sidebar unable to be collapsed:
If fixing this is seen as worth it, then I can work on replicating the style, but for now I think what we have will do (especially when we don't even know for certain what we want the sidebar to look like).
=> Feature: (ISA-144) Removed additional sidebar tabs

frontend/src/cljs/imas_seamap/events.cljs
Small fix for https://jira.its.utas.edu.au/browse/ISA-43
Layer metadata retrieval is now based on whether the metadata url is from IMAS, rather than the category of the layer.
=> Bugfix: (ISA-43) Metadata popups for non-IMAS imagery layers

frontend/src/cljs/imas_seamap/core.cljs, frontend/src/cljs/imas_seamap/db.cljs, frontend/src/cljs/imas_seamap/events.cljs, frontend/src/cljs/imas_seamap/map/events.cljs, frontend/src/cljs/imas_seamap/views.cljs
https://jira.its.utas.edu.au/browse/ISA-135
https://jira.its.utas.edu.au/browse/ISA-32
Just some additional cleanup to remove the last of the category-specific logic that we no longer want. Backend will need to be updated after this merge is made.
=> Feature: (ISA-135) Remove category-specific logic

backend/habitat/viewsets.py, backend/webapp/urls.py, database/Views/SeamapAus_Networks_View.sql, database/Views/SeamapAus_Parks_View.sql, frontend/src/cljs/imas_seamap/core.cljs, frontend/src/cljs/imas_seamap/db.cljs, frontend/src/cljs/imas_seamap/map/events.cljs, frontend/src/cljs/imas_seamap/map/subs.cljs, frontend/src/cljs/imas_seamap/specs/app_state.cljs, frontend/src/cljs/imas_seamap/views.cljs
[ISA-161](https://jira.its.utas.edu.au/browse/ISA-161)
Can now get and display the habitat statistics for a network or park. Statistics are displayed in a table on the state of knowledge sidebar, like so:
Currently does not work for zones. Does not display bathymetry or habitat observations information.
=> Feature: (ISA-161) Query statistics for habitat

frontend/src/cljs/imas_seamap/map/events.cljs, frontend/src/cljs/imas_seamap/map/utils.cljs
[ISA-187](https://jira.its.utas.edu.au/browse/ISA-187)
Simple fix by filtering out layers without a valid info format from the request (strangely, I thought we'd already done that :-/ ).
Fixed now – sorry about the whole pull request, I thought it'd be bigger than one commit.
I believe this solution also fixes [ISA-188](https://jira.its.utas.edu.au/browse/ISA-188), by skipping those buggy requests.
=> Bugfix: (ISA-187) GetFeatureInfo info format request priorities

backend/habitat/viewsets.py, database/Functions/unique_bathymetry_intersections.sql, database/Procedures/UpdateBathymetry.sql, database/Procedures/Update_AMP_BOUNDARY.sql, database/Procedures/Update_IMCRA_BOUNDARY.sql, database/Procedures/Update_MEOW_BOUNDARY.sql, database/Scripts/Fill-bathymetry-geoms-table.sql, database/Scripts/Fill-unique-bathymetry-geoms-table.sql, database/Tables/BOUNDARY_AMP_BATHYMETRY.sql, database/Tables/BOUNDARY_IMCRA_BATHYMETRY.sql, database/Tables/BOUNDARY_MEOW_BATHYMETRY.sql, database/Views/VW_BATHYMETRY.sql, database/Views/VW_BOUNDARY_IMCRA.sql, frontend/src/cljs/imas_seamap/components.cljs, frontend/src/cljs/imas_seamap/map/subs.cljs, frontend/src/cljs/imas_seamap/specs/app_state.cljs, frontend/src/cljs/imas_seamap/views.cljs, frontend/src/ui/css/app.scss
[ISA-186](https://jira.its.utas.edu.au/browse/ISA-186)
The stated visual changes have been made. Several tables in the database have been changed so that the bathymetry category is labeled as the bathymetry resolution on the backend (and there are backend and frontend changes to accomodate this). Final database changes can be made to remove temporary columns, once this is deployed.
=> Feature: (ISA-186) State of knowledge visuals tweak

frontend/src/cljs/imas_seamap/components.cljs, frontend/src/cljs/imas_seamap/core.cljs, frontend/src/cljs/imas_seamap/db.cljs, frontend/src/cljs/imas_seamap/state_of_knowledge/events.cljs, frontend/src/cljs/imas_seamap/state_of_knowledge/subs.cljs, frontend/src/cljs/imas_seamap/state_of_knowledge/views.cljs, frontend/src/cljs/imas_seamap/views.cljs, frontend/src/ui/Select/Select.jsx, frontend/src/ui/Select/Select.stories.jsx, frontend/src/ui/css/app.scss, frontend/src/ui/css/floating-pills.scss, frontend/src/ui/css/state-of-knowledge.scss
Several usability tweaks to the state of knowledge floating pills:
• State of knowledge panel now only opens when a boundary type has been selected
• State of knowledge statistics are shown for the entire region (all boundaries), when no filters are selected
• Floating pill titles show the filters selected in that pill
• Pills automatically close on special logic, specific to each pill (pills 1 and 3 close when a single selection is made, and pill 2 closes when all selections are made).
• "IUCN Category (Zone)" -> "IUCN Category"
• Currently selected boundaries are shown in the state of knowledge panel
◦ New breadcrumbs component to accomplish this
◦ Network and park breadcrumbs have placeholder hyperlinks for their data coverage report pages
• The select fields for selecting the boundary …
=> Feature: (ISA-195) State of knowledge floating pills tweaks

frontend/src/cljs/imas_seamap/core.cljs, frontend/src/cljs/imas_seamap/db.cljs, frontend/src/cljs/imas_seamap/map/views.cljs, frontend/src/cljs/imas_seamap/specs/app_state.cljs, frontend/src/cljs/imas_seamap/state_of_knowledge/events.cljs, frontend/src/cljs/imas_seamap/state_of_knowledge/subs.cljs, frontend/src/cljs/imas_seamap/state_of_knowledge/utils.cljs
[ISA-205](https://jira.its.utas.edu.au/browse/ISA-205)
Using CQL filters on the active boundary layer to show which area is currently being filtered to in the state of knowledge.
Appropriate layer that corresponds with filters is now shown (i.e. showing zones layer when zone filter is selected, park filter when park filter is select, etc.)
=> Feature: (ISA-205) State of knowledge boundary CQL filters

backend/catalogue/management/commands/generate_layer_previews.py
[ISA-55](https://jira.its.utas.edu.au/browse/ISA-55)
The ability to divide the GetMap requests used in the generation of layer preview images has been added. Dividing the GetMap requests into chunks of the final image is useful for retrieving complex layers such as seamap:SeamapAus_TAS_AbHab_substrata_grp and seamap:FINALPRODUCT_SeamapAus_v2.
Layer style has also been added to the parameters for the GetMap request, which affects the display of some layers (e.g. seamap:SeamapAus_BOUNDARIES_AMP2022).
=> Feature: (ISA-55) Divide complex GetMap requests

frontend/src/cljs/imas_seamap/core.cljs, frontend/src/cljs/imas_seamap/interop/leaflet.cljs, frontend/src/cljs/imas_seamap/state_of_knowledge/events.cljs, frontend/src/cljs/imas_seamap/state_of_knowledge/subs.cljs, frontend/src/cljs/imas_seamap/state_of_knowledge/utils.cljs
[ISA-218](https://jira.its.utas.edu.au/browse/ISA-218)
Automatically zooms to the bounds of the selected filters for a state of knowledge boundary. It's a little slow because the WFS GetFeature request is asynchronous, so sometimes it feels weird – I'll let others decide if it feels too weird for users though.
=> Feature: (ISA-218) Zoom selected bounds

frontend/src/cljs/imas_seamap/core.cljs, frontend/src/cljs/imas_seamap/db.cljs, frontend/src/cljs/imas_seamap/events.cljs, frontend/src/cljs/imas_seamap/map/events.cljs, frontend/src/cljs/imas_seamap/map/subs.cljs, frontend/src/cljs/imas_seamap/map/utils.cljs, frontend/src/cljs/imas_seamap/map/views.cljs, frontend/src/cljs/imas_seamap/specs/app_state.cljs, frontend/src/cljs/imas_seamap/views.cljs
[ISA-222](https://jira.its.utas.edu.au/browse/ISA-222)
"Magic mode" has been replaced with an option that only shows layers within the current viewport.
Need to figure out how we're going have the national layer displayed on load – hardcode it as suggested by Emma?
=> Feature: (ISA-222) Replace magic mode

backend/.gitignore, backend/catalogue/management/commands/generate_layer_previews.py, frontend/src/cljs/imas_seamap/map/events.cljs, frontend/src/cljs/imas_seamap/map/utils.cljs, frontend/src/cljs/imas_seamap/map/views.cljs, frontend/src/cljs/imas_seamap/subs.cljs, frontend/src/cljs/imas_seamap/utils.cljs, frontend/src/ui/css/app.scss
[ISA-221](https://jira.its.utas.edu.au/browse/ISA-221)
Thanks to the encapsulation provided by [Shadow-DOM](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM), we can now include the style from GetFeatureInfo responses in addition to their body content. This has fixed the GFI display for a few layers.
Before:
After:
=> Feature: (ISA-221) Include server-set CSS in GetFeatureInfo popup

backend/catalogue/admin.py, backend/catalogue/models.py, backend/catalogue/serializers.py, backend/catalogue/viewsets.py, backend/webapp/urls.py, database/Procedures/UpdateBathymetry.sql, frontend/src/cljs/imas_seamap/core.cljs, frontend/src/cljs/imas_seamap/db.cljs, frontend/src/cljs/imas_seamap/events.cljs, frontend/src/cljs/imas_seamap/map/events.cljs, frontend/src/cljs/imas_seamap/specs/app_state.cljs, frontend/src/cljs/imas_seamap/state_of_knowledge/events.cljs
[ISA-222](https://jira.its.utas.edu.au/browse/ISA-222), [ISA-223](https://jira.its.utas.edu.au/browse/ISA-223), [ISA-225](https://jira.its.utas.edu.au/browse/ISA-225)
It's become increasingly clear that there's a need to be able to have "hardcoded" layers in the app for certain situations (e.g. default layer(s) on startup). This is a problem if IMAS needs to swap out what hardcoded layers are used in the app if they update the layers in the future.
The solution to this is having a fixed-length table with discrete keywords that alias layers that can then be used in the app instead of directly referring to a layer's ID. What this means is that if IMAS needs to switch out a hardcoded layer in the app, all they need to do is update the keyed-layers table.
=> Feature: (ISA-222, ISA-223, & ISA-225) Keyed-layers

frontend/src/cljs/imas_seamap/map/views.cljs, frontend/src/ui/css/app.scss
[ISA-228](https://jira.its.utas.edu.au/browse/ISA-228)
**Prerequisites:** PR #107 (because I didn't want to deal with any merge conflicts)
Feature-info waiting popup is now invisible (only shows loading spinner):
When no results there is no popup:
=> Feature: (ISA-228) Remove no results popup

frontend/src/cljs/imas_seamap/map/layer_views.cljs, frontend/src/cljs/imas_seamap/map/subs.cljs, frontend/src/cljs/imas_seamap/utils.cljs, frontend/src/cljs/imas_seamap/views.cljs, frontend/src/index.scss, frontend/src/ui/SelectionList/SelectionList.css, frontend/src/ui/SelectionList/SelectionList.jsx, frontend/src/ui/css/app.scss, frontend/src/ui/css/layer-card.scss, frontend/src/ui/css/left-drawer.scss, frontend/src/ui/css/state-of-knowledge.scss
[ISA-263](https://jira.its.utas.edu.au/browse/ISA-263)
Messy diffs incoming!
On top of starting a basic UI for a richer main national layer card, a lot of the layer card component stuff has been refactored and should be much neater. Of most note is that the components were cleaned up with descriptions and moved into a separate view file.
As a part of the cleaning, unused components in the old view have been removed, and unused css classes have been removed (there could be selectors that I missed, but I was quite thorough).
Pretty pictures of main national layer card:
The UI elements are "dumb" and don't actually affect the display of the layers in the map – separate ticket when we get to it.
=> Feature: (ISA-263) Richer main national layer card UI

frontend/src/cljs/imas_seamap/core.cljs, frontend/src/cljs/imas_seamap/db.cljs, frontend/src/cljs/imas_seamap/map/events.cljs, frontend/src/cljs/imas_seamap/map/layer_views.cljs, frontend/src/cljs/imas_seamap/map/subs.cljs, frontend/src/cljs/imas_seamap/specs/app_state.cljs, frontend/src/cljs/imas_seamap/views.cljs, frontend/src/ui/css/app.scss
[ISA-256](https://jira.its.utas.edu.au/browse/ISA-256)
Now using vector legends instead of images.
Layers with a custom legend image url (e.g. MODELLED - Aus Bathymetry Grid 2019 - 250m [GA]) will still use the image from the url provided – open to opinions on this.
Before:
After:
=> Feature: (ISA-256) Vector legends

frontend/src/cljs/imas_seamap/core.cljs, frontend/src/cljs/imas_seamap/map/events.cljs, frontend/src/cljs/imas_seamap/map/layer_views.cljs, frontend/src/cljs/imas_seamap/map/subs.cljs, frontend/src/cljs/imas_seamap/specs/app_state.cljs, frontend/src/ui/css/layer-card.scss
[ISA-268](https://jira.its.utas.edu.au/browse/ISA-268)
Vector legend support for feature layers added.
Additionally, we have some semblance of error handling now:
=> Feature: (ISA-268) Feature layer vector legends

.github/workflows/auditrequirements.yml
[ISA-245](https://jira.its.utas.edu.au/browse/ISA-245)
I did some reading on [pip-audit](https://github.com/pypa/gh-action-pip-audit#configuration) and general [GitHub workflow actions syntax](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions) and managed to come up with the following file.
I think it should run Sunday 00:00 every week, and when it does it checks our `deploy_requirements.txt` for any vulnerabilities. We should be able to add vulnerabilities to ignore as needed.
In regards to receiving notifications if the workflow run fails, I believe that would be me [according to this](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/notifications-for-workflow-runs).
=> (ISA-245) pip-audit github action

frontend/src/cljs/imas_seamap/core.cljs, frontend/src/cljs/imas_seamap/db.cljs, frontend/src/cljs/imas_seamap/events.cljs, frontend/src/cljs/imas_seamap/map/events.cljs, frontend/src/cljs/imas_seamap/subs.cljs, frontend/src/cljs/imas_seamap/utils.cljs, frontend/src/cljs/imas_seamap/views.cljs
[ISA-275](https://jira.its.utas.edu.au/browse/ISA-275)
So I'm not certain on my implementation, which is why I'm looking to you for a second opinion.
The way I've done this is I've registered a new event named `:put-hash-if-autosave`, and everything that previously used the `:put-hash` effect now dispatches that event instead.
I was considering registering a new effect for this, but decided against it due to clunkiness (since it would have to check if saves were enabled, encode the state, and put-hash in a single effect – [day8 discourage complex effects like that](https://github.com/day8/re-frame/blob/master/docs/Effects.md#:~:text=A%20word%20of%20advice%20-%20make%20them%20as%20simple%20as%20possible%2C%20and%20then%20simplify%20them%20further.%20You%20don%27t%20want%20them%20containing% …
=> (ISA-275) Optionally remember saved state

frontend/src/cljs/imas_seamap/core.cljs, frontend/src/cljs/imas_seamap/events.cljs, frontend/src/cljs/imas_seamap/map/events.cljs, frontend/src/cljs/imas_seamap/utils.cljs
[ISA-257](https://jira.its.utas.edu.au/browse/ISA-257)
There are a few changes to make this work neatly:
- `:get-save-state` event has been modified so that instead of dispatching a single static event `:load-save-state` on success, the event it dispatches is dynamically set based on a dispatch parameter (so we don't have to make a separate event to grab the hashstate for a shortcode for each thing we want to do with a shortcode).
- The code that extracts the ajax-loaded info from the database in `:re-boot` has been separated into a utility function (and made neater).
- Small map flyTo bugfix, not important
- Most of the `:re-boot` code has been moved into a new event named `:set-state` which sets the state of the application to that of the supplied hashstate.
With all that out of the …
=> (ISA-257) Load state dynamically

frontend/src/cljs/imas_seamap/core.cljs, frontend/src/cljs/imas_seamap/db.cljs, frontend/src/cljs/imas_seamap/events.cljs, frontend/src/cljs/imas_seamap/map/events.cljs, frontend/src/cljs/imas_seamap/specs/app_state.cljs, frontend/src/cljs/imas_seamap/state_of_knowledge/views.cljs, frontend/src/cljs/imas_seamap/story_maps/events.cljs, frontend/src/cljs/imas_seamap/story_maps/subs.cljs, frontend/src/cljs/imas_seamap/story_maps/views.cljs, frontend/src/cljs/imas_seamap/utils.cljs, frontend/src/cljs/imas_seamap/views.cljs, frontend/src/ui/css/app.scss, frontend/src/ui/css/state-of-knowledge.scss, frontend/src/ui/css/story-maps.scss
[ISA-260](https://jira.its.utas.edu.au/browse/ISA-260)
Look at PRs #124 and #126 before this one!
Story map is now shown in the right drawer, with clickable buttons that load different map states.
Start with a story map list.
Open a story map by clicking on it in the list. The map state will automatically change to the one first listed in the story map.
Other map states can be viewed by clicking the buttons.
=> (ISA-260) Open story map in right sidebar

frontend/src/cljs/imas_seamap/map/events.cljs, frontend/src/cljs/imas_seamap/map/layer_views.cljs, frontend/src/cljs/imas_seamap/state_of_knowledge/subs.cljs, frontend/src/cljs/imas_seamap/utils.cljs, frontend/src/ui/css/layer-card.scss
[ISA-282](https://jira.its.utas.edu.au/browse/ISA-282)
Point layer support, and using layer legend image as backup if unsupported by the app.
I did consider using SVGs for the point layer legend keys, but that would take extra time (and I'm not sure how I'd dynamically set something like the stroke and colours based on the source data).
=> Bugfix: (ISA-282) JSON legend fixes

frontend/src/cljs/imas_seamap/core.cljs, frontend/src/cljs/imas_seamap/interop/leaflet.cljs, frontend/src/cljs/imas_seamap/map/events.cljs, frontend/src/cljs/imas_seamap/map/utils.cljs
[ISA-265](https://jira.its.utas.edu.au/browse/ISA-265)
Did a little bit of tidying on the code that gets feature info, so now requests are dispatched in multimethods that depend on the layer info format type (so it should now be extendible to future format types should the need arise).
Can now also handle ESRI layers. It's very handy that L.esri.query returns a FeatureCollection response, since that's what we were already using for the JSON layers. ESRI feature layers responses display the same as the JSON layers.
=> (ISA-265) ESRI GetFeatureInfo equivalent

backend/catalogue/models.py, frontend/src/cljs/imas_seamap/map/layer_views.cljs, frontend/src/cljs/imas_seamap/map/subs.cljs, frontend/src/cljs/imas_seamap/specs/app_state.cljs, frontend/src/ui/css/layer-card.scss
[ISA-296](https://jira.its.utas.edu.au/browse/ISA-296)
Layers can have tooltips now.
Tooltips highlight layers in the catalogue with blue text and italics:
Hovering over the header will display the tooltip:
The national layer also has tooltips for its current state if it displays an alternate view or year:
=> (ISA-296) Catalogue layer tooltips

backend/catalogue/management/commands/generate_pressure_previews.py, wordpress/plugins/region-report/region-report.php, wordpress/plugins/region-report/single-region_report.php, wordpress/plugins/region-report/style.css
[ISA-243](https://jira.its.utas.edu.au/browse/ISA-243)
New widget added to region report pages showing categorised pressure maps for a region:
A new Django management command generates the pressure preview images, much in the same way the layer preview images are generated in the Seamap app.
=> (ISA-243) Region Report Pressures

frontend/src/cljs/imas_seamap/events.cljs, frontend/src/cljs/imas_seamap/story_maps/views.cljs, frontend/src/index.scss, frontend/src/ui/blueprint.scss, frontend/src/ui/css/app.scss, frontend/src/ui/css/story-maps.scss
(Probably should be done after #151)
Doing a UX sweep on the story maps drawer to closely match Nat's design.
Nat's design:
Seamap app:
While Blueprint allows the use of variables to tweak a few aspects of an application, I've noticed that it's not perfect and that they don't have free customisation over all the aspects we need. It'd probably be best to organise the I've added CSS responsible for overriding Blueprint into its own file.
=> UX Sweep: Story Maps

frontend/src/cljs/imas_seamap/map/events.cljs, frontend/src/cljs/imas_seamap/utils.cljs
[ISA-429](https://jira.its.utas.edu.au/browse/ISA-429)
Adds legend support for feature server layers, which were previously broken due to utilising the same approach as map server layers.
=> (ISA-429) FeatureServer legend fix

backend/base_requirements.txt
No refactorings or fixes needed so far
=> Django: jump to next major LTS (4.2)

frontend/src/cljs/imas_seamap/analytics.cljs, frontend/src/cljs/imas_seamap/tas_marine_atlas/core.cljs
[ISA-603: TMA Google Analytics report](https://utas.atlassian.net/browse/ISA-603)
Some changes to analytics to accomodate for the new metrics that TMA want to track in the Google Analytics reports.
Added new `layer_display_name` property to layer events, since layer events for non-WMS layers won't really have a `layer_name` property to distinguish the layers with.
=> ISA-603: TMA Google Analytics report
